# Константы для рецептов
MAX_RECIPE_NAME_LEN = 256
MAX_INGREDIENT_NAME_LEN = 128
MAX_MEASUREMENT_UNIT_LEN = 64
MIN_COOKING_TIME = 1
MIN_INGREDIENT_FROM_RECIPES = 1
MAX_SHORT_CODE_LEN = 6

# Константы для моделей юзера
MAX_USER_EMAIL_LEN = 254
MAX_USER_USERNAME_LEN = 150
MAX_USER_FIRST_NAME_LEN = 150
MAX_USER_LAST_NAME_LEN = 150
